# Based on https://github.com/dayanch96/YTLite/blob/main/.github/workflows/main.yml

name: Build app

on:
  workflow_dispatch:
    inputs:
      sdk_version:
        description: "iOS SDK Version"
        default: "15.6"
        required: true
        type: string
      decrypted_app_url:
        description: "Direct URL of the decrypted iPA"
        default: ""
        required: true
        type: string
      commit_id:
        description: "(Optional) Commit ID to build at"
        default: ""
        required: false
        type: string
      upload_artifact:
        description: "Upload iPA as artifact"
        default: true
        required: false
        type: boolean
  
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build app
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
      - name: Checkout to xhs-tweak subfolder
        uses: actions/checkout@v4
        with:
          path: xhs-tweak

      - name: Install Dependencies
        run: brew install make ldid

      - name: Setup Theos
        uses: actions/checkout@v4
        with:
          repository: theos/theos
          path: ${{ github.workspace }}/theos
          submodules: recursive
      
      - name: SDK Caching
        id: SDK
        uses: actions/cache@v4
        env:
          cache-name: iOS-${{ inputs.sdk_version }}-SDK
        with:
          path: theos/sdks/
          key: ${{ env.cache-name }}
          restore-keys: ${{ env.cache-name }}

      - name: Download iOS SDK
        if: steps.SDK.outputs.cache-hit != 'true'
        env:
          THEOS: ${{ github.workspace }}/theos
        run: |
          git clone --quiet -n --depth=1 --filter=tree:0 https://github.com/theos/sdks/
          cd sdks
          git sparse-checkout set --no-cone iPhoneOS${{ inputs.sdk_version }}.sdk
          git checkout
          mv *.sdk $THEOS/sdks

      - name: Install cyan
        run: pipx install --force https://github.com/asdfzxcvbn/pyzule-rw/archive/main.zip

      - name: Download and validate IPA
        run: |
          wget "${{ inputs.ipa_url }}" --no-verbose -O ${{ github.workspace }}/xhs.ipa

          file_type=$(file --mime-type -b ${{ github.workspace }}/xhs.ipa)

          if [[ "$file_type" != "application/x-ios-app" && "$file_type" != "application/zip" ]]; then
            echo "::error::Validation failed: The downloaded file is not a valid IPA. Detected type: $file_type."
            exit 1
          fi

      - name: Build Tweak
        run: |
          cd ${{ github.workspace }}/xhs-tweak
          make clean package DEBUG=0 FINALPACKAGE=1
          mv packages/*.deb ${{ github.workspace }}/xhs-tweak.deb
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Inject tweak into IPA
        run: |
          cyan -i xhs.ipa -o "小小红书.ipa" -uwef xhs-tweak.deb -n "小小红书" -b com.xingin.discover

      - name: Upload Artifact
        if: ${{ inputs.upload_artifact }}
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: ${{ github.workspace }}/"小小红书.ipa"
          if-no-files-found: error
