# Original idea by @ISnackable. Thanks to him for handling the hardest parts!
# https://github.com/ISnackable/YTCubePlus/blob/main/.github/workflows/Build.yml

name: Build and Release app

on:
  workflow_dispatch:
    inputs:
      sdk_version:
        description: "iOS SDK Version"
        default: "16.5"
        required: true
        type: string
      decrypted_app_url:
        description: "Direct URL of the decrypted iPA"
        default: ""
        required: true
        type: string
      commit_id:
        description: "(Optional) Commit ID to build at"
        default: ""
        required: false
        type: string
      upload_artifact:
        description: "Upload iPA as artifact"
        default: true
        required: false
        type: boolean
  
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build app
    runs-on: macos-13
    permissions:
      contents: write

    steps:
      - name: Checkout Main
        uses: actions/checkout@v4.1.7
        with:
          path: main
          ref: ${{ github.event.inputs.commit_id || github.ref }}
          submodules: recursive

      - name: Install Dependencies
        run: brew install ldid dpkg make

      - name: Set PATH environment variable to fix building
        run: echo "$(brew --prefix make)/libexec/gnubin" >> $GITHUB_PATH 

      - name: Setup Theos
        uses: actions/checkout@v4.1.7
        with:
          repository: theos/theos
          ref: 5bfdc3cb7133ec1cab43182115d902e2b57c9eac
          path: theos
          submodules: recursive
      
      - name: SDK Caching
        id: SDK
        uses: actions/cache@v4.0.2
        env:
          cache-name: iOS-${{ inputs.sdk_version }}-SDK
        with:
          path: theos/sdks/
          key: ${{ env.cache-name }}
          restore-keys: ${{ env.cache-name }}

      - name: Download iOS SDK
        if: steps.SDK.outputs.cache-hit != 'true'
        env:
          THEOS: ${{ github.workspace }}/theos
        run: |
          git clone --quiet -n --depth=1 --filter=tree:0 https://github.com/theos/sdks/
          cd sdks
          git sparse-checkout set --no-cone iPhoneOS${{ inputs.sdk_version }}.sdk
          git checkout
          mv *.sdk $THEOS/sdks

      - name: Setup Theos Jailed
        uses: actions/checkout@v4.1.7
        with:
          repository: qnblackcat/theos-jailed
          ref: master
          path: theos-jailed
          submodules: recursive

      - name: Install Theos Jailed
        env:
          THEOS: ${{ github.workspace }}/theos
        run: |
          ./theos-jailed/install


      - name: Prepare iPA
        id: prepare_ipa
        env:
          THEOS: ${{ github.workspace }}/theos
          APP_URL: ${{ inputs.decrypted_app_url }}
        run: |
          wget "$APP_URL" --no-verbose -O main/YouTube.ipa
          cd ${{ github.workspace }}/main
          mv YouTube.ipa YouTube.zip
          unzip YouTube.zip

      - name: Build Package
        id: build_package
        env:
          THEOS: ${{ github.workspace }}/theos
        run: |
          cd ${{ github.workspace }}/main
          make package THEOS_PACKAGE_SCHEME=rootless IPA=Payload/discover.app FINALPACKAGE=1
          echo "package=$(ls -t packages | head -n1)" >>$GITHUB_OUTPUT
          echo -e "==> \033[1mSHASUM256: $(shasum -a 256 packages/*.ipa | cut -f1 -d' ')\033[0m"

      - name: Upload Artifact
        if: ${{ inputs.upload_artifact }}
        uses: actions/upload-artifact@v4.3.3
        with:
          name: app
          path: ${{ github.workspace }}/main/packages/${{ steps.build_package.outputs.package }}
          if-no-files-found: error
